name: assignment_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  hive_flutter: ^1.1.0
  intl:
  hive: ^2.2.3
  cached_network_image: ^3.2.3
  
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
